FROM python:3.8.3
RUN pip install -i https://mirrors.aliyun.com/pypi/simple --upgrade pip
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN  pip install --upgrade pip
RUN  pip install flask && pip install selenium
