// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hall.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Public struct {
	CrateTime            int64    `protobuf:"varint,1,opt,name=crateTime,proto3" json:"crateTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,2,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	DeleteTime           int64    `protobuf:"varint,3,opt,name=deleteTime,proto3" json:"deleteTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Public) Reset()         { *m = Public{} }
func (m *Public) String() string { return proto.CompactTextString(m) }
func (*Public) ProtoMessage()    {}
func (*Public) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{0}
}

func (m *Public) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Public.Unmarshal(m, b)
}
func (m *Public) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Public.Marshal(b, m, deterministic)
}
func (m *Public) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Public.Merge(m, src)
}
func (m *Public) XXX_Size() int {
	return xxx_messageInfo_Public.Size(m)
}
func (m *Public) XXX_DiscardUnknown() {
	xxx_messageInfo_Public.DiscardUnknown(m)
}

var xxx_messageInfo_Public proto.InternalMessageInfo

func (m *Public) GetCrateTime() int64 {
	if m != nil {
		return m.CrateTime
	}
	return 0
}

func (m *Public) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Public) GetDeleteTime() int64 {
	if m != nil {
		return m.DeleteTime
	}
	return 0
}

// RoomUpdateRequest 更新房间信息请求
type RoomUpdateRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	UserList             []string `protobuf:"bytes,2,rep,name=userList,proto3" json:"userList,omitempty"`
	SitDownUsers         []string `protobuf:"bytes,3,rep,name=sitDownUsers,proto3" json:"sitDownUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomUpdateRequest) Reset()         { *m = RoomUpdateRequest{} }
func (m *RoomUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RoomUpdateRequest) ProtoMessage()    {}
func (*RoomUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{1}
}

func (m *RoomUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUpdateRequest.Unmarshal(m, b)
}
func (m *RoomUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUpdateRequest.Marshal(b, m, deterministic)
}
func (m *RoomUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUpdateRequest.Merge(m, src)
}
func (m *RoomUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_RoomUpdateRequest.Size(m)
}
func (m *RoomUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUpdateRequest proto.InternalMessageInfo

func (m *RoomUpdateRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *RoomUpdateRequest) GetUserList() []string {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *RoomUpdateRequest) GetSitDownUsers() []string {
	if m != nil {
		return m.SitDownUsers
	}
	return nil
}

// RoomAddRequest 添加一个房间
type RoomAddRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAddRequest) Reset()         { *m = RoomAddRequest{} }
func (m *RoomAddRequest) String() string { return proto.CompactTextString(m) }
func (*RoomAddRequest) ProtoMessage()    {}
func (*RoomAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{2}
}

func (m *RoomAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAddRequest.Unmarshal(m, b)
}
func (m *RoomAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAddRequest.Marshal(b, m, deterministic)
}
func (m *RoomAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAddRequest.Merge(m, src)
}
func (m *RoomAddRequest) XXX_Size() int {
	return xxx_messageInfo_RoomAddRequest.Size(m)
}
func (m *RoomAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAddRequest proto.InternalMessageInfo

func (m *RoomAddRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// RoomResponse
type RoomResponse struct {
	Base                 *Public   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Rid                  string    `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	RoomTypeID           int32     `protobuf:"varint,3,opt,name=roomTypeID,proto3" json:"roomTypeID,omitempty"`
	CreateUid            string    `protobuf:"bytes,4,opt,name=createUid,proto3" json:"createUid,omitempty"`
	CanNotBetting        bool      `protobuf:"varint,5,opt,name=canNotBetting,proto3" json:"canNotBetting,omitempty"`
	PlayModeId           int32     `protobuf:"varint,6,opt,name=playModeId,proto3" json:"playModeId,omitempty"`
	ChipTotal            float32   `protobuf:"fixed32,7,opt,name=chipTotal,proto3" json:"chipTotal,omitempty"`
	Status               int32     `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	Meta                 *RoomMeta `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomResponse) Reset()         { *m = RoomResponse{} }
func (m *RoomResponse) String() string { return proto.CompactTextString(m) }
func (*RoomResponse) ProtoMessage()    {}
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{3}
}

func (m *RoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResponse.Unmarshal(m, b)
}
func (m *RoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResponse.Marshal(b, m, deterministic)
}
func (m *RoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResponse.Merge(m, src)
}
func (m *RoomResponse) XXX_Size() int {
	return xxx_messageInfo_RoomResponse.Size(m)
}
func (m *RoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResponse proto.InternalMessageInfo

func (m *RoomResponse) GetBase() *Public {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RoomResponse) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *RoomResponse) GetRoomTypeID() int32 {
	if m != nil {
		return m.RoomTypeID
	}
	return 0
}

func (m *RoomResponse) GetCreateUid() string {
	if m != nil {
		return m.CreateUid
	}
	return ""
}

func (m *RoomResponse) GetCanNotBetting() bool {
	if m != nil {
		return m.CanNotBetting
	}
	return false
}

func (m *RoomResponse) GetPlayModeId() int32 {
	if m != nil {
		return m.PlayModeId
	}
	return 0
}

func (m *RoomResponse) GetChipTotal() float32 {
	if m != nil {
		return m.ChipTotal
	}
	return 0
}

func (m *RoomResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomResponse) GetMeta() *RoomMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// RoomMeta
type RoomMeta struct {
	SitDownUsers         []string `protobuf:"bytes,1,rep,name=sitDownUsers,proto3" json:"sitDownUsers,omitempty"`
	UserList             []string `protobuf:"bytes,2,rep,name=userList,proto3" json:"userList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMeta) Reset()         { *m = RoomMeta{} }
func (m *RoomMeta) String() string { return proto.CompactTextString(m) }
func (*RoomMeta) ProtoMessage()    {}
func (*RoomMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{4}
}

func (m *RoomMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMeta.Unmarshal(m, b)
}
func (m *RoomMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMeta.Marshal(b, m, deterministic)
}
func (m *RoomMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMeta.Merge(m, src)
}
func (m *RoomMeta) XXX_Size() int {
	return xxx_messageInfo_RoomMeta.Size(m)
}
func (m *RoomMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMeta proto.InternalMessageInfo

func (m *RoomMeta) GetSitDownUsers() []string {
	if m != nil {
		return m.SitDownUsers
	}
	return nil
}

func (m *RoomMeta) GetUserList() []string {
	if m != nil {
		return m.UserList
	}
	return nil
}

type RoomExistRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomExistRequest) Reset()         { *m = RoomExistRequest{} }
func (m *RoomExistRequest) String() string { return proto.CompactTextString(m) }
func (*RoomExistRequest) ProtoMessage()    {}
func (*RoomExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{5}
}

func (m *RoomExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomExistRequest.Unmarshal(m, b)
}
func (m *RoomExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomExistRequest.Marshal(b, m, deterministic)
}
func (m *RoomExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomExistRequest.Merge(m, src)
}
func (m *RoomExistRequest) XXX_Size() int {
	return xxx_messageInfo_RoomExistRequest.Size(m)
}
func (m *RoomExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomExistRequest proto.InternalMessageInfo

func (m *RoomExistRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *RoomExistRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// RoomGetRequest
type RoomGetRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomGetRequest) Reset()         { *m = RoomGetRequest{} }
func (m *RoomGetRequest) String() string { return proto.CompactTextString(m) }
func (*RoomGetRequest) ProtoMessage()    {}
func (*RoomGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{6}
}

func (m *RoomGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomGetRequest.Unmarshal(m, b)
}
func (m *RoomGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomGetRequest.Marshal(b, m, deterministic)
}
func (m *RoomGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomGetRequest.Merge(m, src)
}
func (m *RoomGetRequest) XXX_Size() int {
	return xxx_messageInfo_RoomGetRequest.Size(m)
}
func (m *RoomGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomGetRequest proto.InternalMessageInfo

func (m *RoomGetRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

// UserGetRequest
type UserGetRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{7}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

// UserResponse
type UserResponse struct {
	Base                 *Public     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Uid                  string      `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               int32       `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Level                int32       `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Consume              int64       `protobuf:"varint,5,opt,name=consume,proto3" json:"consume,omitempty"`
	TotalWin             int64       `protobuf:"varint,6,opt,name=totalWin,proto3" json:"totalWin,omitempty"`
	TotalCommission      int64       `protobuf:"varint,7,opt,name=totalCommission,proto3" json:"totalCommission,omitempty"`
	TotalCash            int64       `protobuf:"varint,8,opt,name=totalCash,proto3" json:"totalCash,omitempty"`
	FreeChipStartTime    int64       `protobuf:"varint,9,opt,name=freeChipStartTime,proto3" json:"freeChipStartTime,omitempty"`
	FreeChipLeftTime     int64       `protobuf:"varint,10,opt,name=freeChipLeftTime,proto3" json:"freeChipLeftTime,omitempty"`
	SavingPotChips       int64       `protobuf:"varint,11,opt,name=savingPotChips,proto3" json:"savingPotChips,omitempty"`
	AccountType          string      `protobuf:"bytes,12,opt,name=accountType,proto3" json:"accountType,omitempty"`
	IsForbidden          bool        `protobuf:"varint,13,opt,name=isForbidden,proto3" json:"isForbidden,omitempty"`
	IsBot                bool        `protobuf:"varint,14,opt,name=isBot,proto3" json:"isBot,omitempty"`
	LastLoginTime        int64       `protobuf:"varint,15,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	LastGameTime         int64       `protobuf:"varint,16,opt,name=lastGameTime,proto3" json:"lastGameTime,omitempty"`
	OfflineTime          int64       `protobuf:"varint,17,opt,name=offlineTime,proto3" json:"offlineTime,omitempty"`
	Parent               string      `protobuf:"bytes,18,opt,name=parent,proto3" json:"parent,omitempty"`
	Meta                 *UserMeta   `protobuf:"bytes,19,opt,name=meta,proto3" json:"meta,omitempty"`
	UserDetail           *UserDetail `protobuf:"bytes,20,opt,name=userDetail,proto3" json:"userDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{8}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetBase() *Public {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserResponse) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserResponse) GetConsume() int64 {
	if m != nil {
		return m.Consume
	}
	return 0
}

func (m *UserResponse) GetTotalWin() int64 {
	if m != nil {
		return m.TotalWin
	}
	return 0
}

func (m *UserResponse) GetTotalCommission() int64 {
	if m != nil {
		return m.TotalCommission
	}
	return 0
}

func (m *UserResponse) GetTotalCash() int64 {
	if m != nil {
		return m.TotalCash
	}
	return 0
}

func (m *UserResponse) GetFreeChipStartTime() int64 {
	if m != nil {
		return m.FreeChipStartTime
	}
	return 0
}

func (m *UserResponse) GetFreeChipLeftTime() int64 {
	if m != nil {
		return m.FreeChipLeftTime
	}
	return 0
}

func (m *UserResponse) GetSavingPotChips() int64 {
	if m != nil {
		return m.SavingPotChips
	}
	return 0
}

func (m *UserResponse) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *UserResponse) GetIsForbidden() bool {
	if m != nil {
		return m.IsForbidden
	}
	return false
}

func (m *UserResponse) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *UserResponse) GetLastLoginTime() int64 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

func (m *UserResponse) GetLastGameTime() int64 {
	if m != nil {
		return m.LastGameTime
	}
	return 0
}

func (m *UserResponse) GetOfflineTime() int64 {
	if m != nil {
		return m.OfflineTime
	}
	return 0
}

func (m *UserResponse) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *UserResponse) GetMeta() *UserMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserResponse) GetUserDetail() *UserDetail {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

type UserMeta struct {
	ForbiddenTime        int64    `protobuf:"varint,1,opt,name=forbiddenTime,proto3" json:"forbiddenTime,omitempty"`
	ForbiddenDesc        string   `protobuf:"bytes,2,opt,name=forbiddenDesc,proto3" json:"forbiddenDesc,omitempty"`
	ImHeadURL            string   `protobuf:"bytes,3,opt,name=ImHeadURL,proto3" json:"ImHeadURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{9}
}

func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

func (m *UserMeta) GetForbiddenTime() int64 {
	if m != nil {
		return m.ForbiddenTime
	}
	return 0
}

func (m *UserMeta) GetForbiddenDesc() string {
	if m != nil {
		return m.ForbiddenDesc
	}
	return ""
}

func (m *UserMeta) GetImHeadURL() string {
	if m != nil {
		return m.ImHeadURL
	}
	return ""
}

type UserDetail struct {
	Base                 *Public  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	IsChangeUsername     bool     `protobuf:"varint,5,opt,name=isChangeUsername,proto3" json:"isChangeUsername,omitempty"`
	RealName             string   `protobuf:"bytes,6,opt,name=realName,proto3" json:"realName,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	HeadIcon             string   `protobuf:"bytes,8,opt,name=headIcon,proto3" json:"headIcon,omitempty"`
	Email                string   `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	LoginPassword        string   `protobuf:"bytes,10,opt,name=loginPassword,proto3" json:"loginPassword,omitempty"`
	PayPassword          string   `protobuf:"bytes,11,opt,name=payPassword,proto3" json:"payPassword,omitempty"`
	IsLogout             bool     `protobuf:"varint,12,opt,name=isLogout,proto3" json:"isLogout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{10}
}

func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (m *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(m, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetBase() *Public {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserDetail) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserDetail) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserDetail) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserDetail) GetIsChangeUsername() bool {
	if m != nil {
		return m.IsChangeUsername
	}
	return false
}

func (m *UserDetail) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *UserDetail) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserDetail) GetHeadIcon() string {
	if m != nil {
		return m.HeadIcon
	}
	return ""
}

func (m *UserDetail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDetail) GetLoginPassword() string {
	if m != nil {
		return m.LoginPassword
	}
	return ""
}

func (m *UserDetail) GetPayPassword() string {
	if m != nil {
		return m.PayPassword
	}
	return ""
}

func (m *UserDetail) GetIsLogout() bool {
	if m != nil {
		return m.IsLogout
	}
	return false
}

type WalletResponse struct {
	Base                 *Public  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	IsFreeze             bool     `protobuf:"varint,3,opt,name=isFreeze,proto3" json:"isFreeze,omitempty"`
	Balance              float32  `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty"`
	WalletType           string   `protobuf:"bytes,5,opt,name=walletType,proto3" json:"walletType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletResponse) Reset()         { *m = WalletResponse{} }
func (m *WalletResponse) String() string { return proto.CompactTextString(m) }
func (*WalletResponse) ProtoMessage()    {}
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{11}
}

func (m *WalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletResponse.Unmarshal(m, b)
}
func (m *WalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletResponse.Marshal(b, m, deterministic)
}
func (m *WalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletResponse.Merge(m, src)
}
func (m *WalletResponse) XXX_Size() int {
	return xxx_messageInfo_WalletResponse.Size(m)
}
func (m *WalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalletResponse proto.InternalMessageInfo

func (m *WalletResponse) GetBase() *Public {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *WalletResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WalletResponse) GetIsFreeze() bool {
	if m != nil {
		return m.IsFreeze
	}
	return false
}

func (m *WalletResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *WalletResponse) GetWalletType() string {
	if m != nil {
		return m.WalletType
	}
	return ""
}

type WalletListResponse struct {
	List                 []*WalletResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WalletListResponse) Reset()         { *m = WalletListResponse{} }
func (m *WalletListResponse) String() string { return proto.CompactTextString(m) }
func (*WalletListResponse) ProtoMessage()    {}
func (*WalletListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{12}
}

func (m *WalletListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletListResponse.Unmarshal(m, b)
}
func (m *WalletListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletListResponse.Marshal(b, m, deterministic)
}
func (m *WalletListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletListResponse.Merge(m, src)
}
func (m *WalletListResponse) XXX_Size() int {
	return xxx_messageInfo_WalletListResponse.Size(m)
}
func (m *WalletListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalletListResponse proto.InternalMessageInfo

func (m *WalletListResponse) GetList() []*WalletResponse {
	if m != nil {
		return m.List
	}
	return nil
}

type WalletGetByWidRequest struct {
	Wid                  string   `protobuf:"bytes,1,opt,name=wid,proto3" json:"wid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletGetByWidRequest) Reset()         { *m = WalletGetByWidRequest{} }
func (m *WalletGetByWidRequest) String() string { return proto.CompactTextString(m) }
func (*WalletGetByWidRequest) ProtoMessage()    {}
func (*WalletGetByWidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{13}
}

func (m *WalletGetByWidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletGetByWidRequest.Unmarshal(m, b)
}
func (m *WalletGetByWidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletGetByWidRequest.Marshal(b, m, deterministic)
}
func (m *WalletGetByWidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletGetByWidRequest.Merge(m, src)
}
func (m *WalletGetByWidRequest) XXX_Size() int {
	return xxx_messageInfo_WalletGetByWidRequest.Size(m)
}
func (m *WalletGetByWidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletGetByWidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalletGetByWidRequest proto.InternalMessageInfo

func (m *WalletGetByWidRequest) GetWid() string {
	if m != nil {
		return m.Wid
	}
	return ""
}

type WalletGetByUIDRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletGetByUIDRequest) Reset()         { *m = WalletGetByUIDRequest{} }
func (m *WalletGetByUIDRequest) String() string { return proto.CompactTextString(m) }
func (*WalletGetByUIDRequest) ProtoMessage()    {}
func (*WalletGetByUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{14}
}

func (m *WalletGetByUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletGetByUIDRequest.Unmarshal(m, b)
}
func (m *WalletGetByUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletGetByUIDRequest.Marshal(b, m, deterministic)
}
func (m *WalletGetByUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletGetByUIDRequest.Merge(m, src)
}
func (m *WalletGetByUIDRequest) XXX_Size() int {
	return xxx_messageInfo_WalletGetByUIDRequest.Size(m)
}
func (m *WalletGetByUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletGetByUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalletGetByUIDRequest proto.InternalMessageInfo

func (m *WalletGetByUIDRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CheckTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRequest) Reset()         { *m = CheckTokenRequest{} }
func (m *CheckTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRequest) ProtoMessage()    {}
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{15}
}

func (m *CheckTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRequest.Unmarshal(m, b)
}
func (m *CheckTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRequest.Marshal(b, m, deterministic)
}
func (m *CheckTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRequest.Merge(m, src)
}
func (m *CheckTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRequest.Size(m)
}
func (m *CheckTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRequest proto.InternalMessageInfo

func (m *CheckTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckTokenResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenResponse) Reset()         { *m = CheckTokenResponse{} }
func (m *CheckTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResponse) ProtoMessage()    {}
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e141f6d4a8804e5, []int{16}
}

func (m *CheckTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResponse.Unmarshal(m, b)
}
func (m *CheckTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResponse.Marshal(b, m, deterministic)
}
func (m *CheckTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResponse.Merge(m, src)
}
func (m *CheckTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResponse.Size(m)
}
func (m *CheckTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResponse proto.InternalMessageInfo

func (m *CheckTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Public)(nil), "docsGrpc.Public")
	proto.RegisterType((*RoomUpdateRequest)(nil), "docsGrpc.RoomUpdateRequest")
	proto.RegisterType((*RoomAddRequest)(nil), "docsGrpc.RoomAddRequest")
	proto.RegisterType((*RoomResponse)(nil), "docsGrpc.RoomResponse")
	proto.RegisterType((*RoomMeta)(nil), "docsGrpc.RoomMeta")
	proto.RegisterType((*RoomExistRequest)(nil), "docsGrpc.RoomExistRequest")
	proto.RegisterType((*RoomGetRequest)(nil), "docsGrpc.RoomGetRequest")
	proto.RegisterType((*UserGetRequest)(nil), "docsGrpc.UserGetRequest")
	proto.RegisterType((*UserResponse)(nil), "docsGrpc.UserResponse")
	proto.RegisterType((*UserMeta)(nil), "docsGrpc.UserMeta")
	proto.RegisterType((*UserDetail)(nil), "docsGrpc.UserDetail")
	proto.RegisterType((*WalletResponse)(nil), "docsGrpc.WalletResponse")
	proto.RegisterType((*WalletListResponse)(nil), "docsGrpc.WalletListResponse")
	proto.RegisterType((*WalletGetByWidRequest)(nil), "docsGrpc.WalletGetByWidRequest")
	proto.RegisterType((*WalletGetByUIDRequest)(nil), "docsGrpc.WalletGetByUIDRequest")
	proto.RegisterType((*CheckTokenRequest)(nil), "docsGrpc.CheckTokenRequest")
	proto.RegisterType((*CheckTokenResponse)(nil), "docsGrpc.CheckTokenResponse")
}

func init() { proto.RegisterFile("hall.proto", fileDescriptor_4e141f6d4a8804e5) }

var fileDescriptor_4e141f6d4a8804e5 = []byte{
	// 1112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0xfe, 0x6c, 0x71, 0xec, 0x38, 0xf6, 0xd6, 0x0d, 0x08, 0x35, 0x48, 0x0d, 0x22, 0x08,
	0x9c, 0x20, 0xf0, 0xc1, 0x2d, 0x7a, 0x0b, 0xd0, 0xda, 0x4e, 0x1c, 0x15, 0xb2, 0x61, 0xac, 0x2d,
	0xf8, 0xbc, 0x26, 0x57, 0xd2, 0xc2, 0x14, 0x97, 0xe5, 0xae, 0xa2, 0xb8, 0x0f, 0xd3, 0x73, 0x8f,
	0x3d, 0xf7, 0xa9, 0xfa, 0x08, 0xc5, 0xcc, 0x92, 0x22, 0x29, 0xc5, 0x2e, 0xda, 0xde, 0x38, 0xdf,
	0x7c, 0x3b, 0x3b, 0x3b, 0xbf, 0x04, 0x98, 0x88, 0x38, 0x3e, 0x4c, 0x33, 0x6d, 0x35, 0xeb, 0x46,
	0x3a, 0x34, 0x67, 0x59, 0x1a, 0x06, 0x23, 0x58, 0xbf, 0x9c, 0xdd, 0xc6, 0x2a, 0x64, 0xcf, 0xc1,
	0x0b, 0x33, 0x61, 0xe5, 0xb5, 0x9a, 0x4a, 0xbf, 0xb1, 0xdf, 0x38, 0x68, 0xf1, 0x12, 0x60, 0x2f,
	0x00, 0x66, 0x69, 0x54, 0xa8, 0x9b, 0xa4, 0xae, 0x20, 0xa8, 0x8f, 0x64, 0x2c, 0x73, 0x7d, 0xcb,
	0xe9, 0x4b, 0x24, 0x90, 0xb0, 0xcb, 0xb5, 0x9e, 0x0e, 0xe9, 0x04, 0x97, 0xbf, 0xcc, 0xa4, 0xb1,
	0x6c, 0x07, 0x5a, 0x99, 0x8a, 0xe8, 0x32, 0x8f, 0xe3, 0x27, 0xeb, 0x41, 0x77, 0x66, 0x64, 0x36,
	0x50, 0xc6, 0xfa, 0xcd, 0xfd, 0xd6, 0x81, 0xc7, 0x17, 0x32, 0x0b, 0x60, 0xcb, 0x28, 0x7b, 0xaa,
	0xe7, 0xc9, 0xd0, 0xc8, 0xcc, 0xf8, 0x2d, 0xd2, 0xd7, 0xb0, 0x20, 0x80, 0x6d, 0xbc, 0xe6, 0xa7,
	0x28, 0xaa, 0xdc, 0x31, 0x2b, 0xef, 0x98, 0xa9, 0x28, 0xf8, 0xbd, 0x09, 0x5b, 0x48, 0xe2, 0xd2,
	0xa4, 0x3a, 0x31, 0x92, 0xbd, 0x84, 0xf6, 0xad, 0x30, 0xee, 0xd1, 0x9b, 0x47, 0x3b, 0x87, 0x45,
	0x70, 0x0e, 0x5d, 0x64, 0x38, 0x69, 0x0b, 0x67, 0x9b, 0xa5, 0xb3, 0x2f, 0x00, 0x32, 0xad, 0xa7,
	0xd7, 0xf7, 0xa9, 0xec, 0x9f, 0xd2, 0x9b, 0x3b, 0xbc, 0x82, 0xb8, 0x88, 0x4a, 0x61, 0xe5, 0x50,
	0x45, 0x7e, 0x9b, 0xce, 0x95, 0x00, 0x7b, 0x09, 0x4f, 0x42, 0x91, 0x5c, 0x68, 0x7b, 0x2c, 0xad,
	0x55, 0xc9, 0xd8, 0xef, 0xec, 0x37, 0x0e, 0xba, 0xbc, 0x0e, 0xe2, 0x1d, 0x69, 0x2c, 0xee, 0xcf,
	0x75, 0x24, 0xfb, 0x91, 0xbf, 0xee, 0xee, 0x28, 0x11, 0xba, 0x63, 0xa2, 0xd2, 0x6b, 0x6d, 0x45,
	0xec, 0x6f, 0xec, 0x37, 0x0e, 0x9a, 0xbc, 0x04, 0xd8, 0x33, 0x58, 0xbf, 0xb2, 0xc2, 0xce, 0x8c,
	0xdf, 0xa5, 0x93, 0xb9, 0xc4, 0x5e, 0x41, 0x7b, 0x2a, 0xad, 0xf0, 0x3d, 0x7a, 0x31, 0x2b, 0x5f,
	0x8c, 0x71, 0x39, 0x97, 0x56, 0x70, 0xd2, 0x07, 0x3f, 0x43, 0xb7, 0x40, 0x56, 0xc2, 0xdf, 0x58,
	0x0d, 0xff, 0x63, 0xe9, 0x0b, 0x7e, 0x80, 0x1d, 0xb4, 0xf5, 0xfe, 0xb3, 0x32, 0xf6, 0xe1, 0x02,
	0xc8, 0xd3, 0xd5, 0x2c, 0xd3, 0x95, 0xa7, 0xf4, 0x4c, 0x3e, 0x7c, 0x0a, 0x39, 0xe8, 0x40, 0x9d,
	0xb3, 0x94, 0xf6, 0x3f, 0x3a, 0xb0, 0x85, 0xa4, 0x7f, 0x9f, 0xf6, 0xba, 0x43, 0x18, 0x54, 0xe3,
	0x82, 0xea, 0x52, 0x9e, 0x4b, 0x6c, 0x0f, 0x3a, 0xb1, 0xfc, 0x24, 0x63, 0x4a, 0x75, 0x87, 0x3b,
	0x81, 0xf9, 0xb0, 0x11, 0xea, 0xc4, 0xcc, 0xa6, 0x92, 0x12, 0xdc, 0xe2, 0x85, 0x88, 0xc1, 0xb2,
	0x98, 0xa5, 0x1b, 0x95, 0x50, 0x62, 0x5b, 0x7c, 0x21, 0xb3, 0x03, 0x78, 0x4a, 0xdf, 0x27, 0x7a,
	0x3a, 0x55, 0xc6, 0x28, 0x9d, 0x50, 0x72, 0x5b, 0x7c, 0x19, 0xc6, 0x02, 0x70, 0x90, 0x30, 0x13,
	0xca, 0x72, 0x8b, 0x97, 0x00, 0x7b, 0x0b, 0xbb, 0xa3, 0x4c, 0xca, 0x93, 0x89, 0x4a, 0xaf, 0xac,
	0xc8, 0x2c, 0x75, 0xa7, 0x47, 0xac, 0x55, 0x05, 0x7b, 0x03, 0x3b, 0x05, 0x38, 0x90, 0x23, 0x47,
	0x06, 0x22, 0xaf, 0xe0, 0xec, 0x15, 0x6c, 0x1b, 0xf1, 0x49, 0x25, 0xe3, 0x4b, 0x6d, 0x51, 0x61,
	0xfc, 0x4d, 0x62, 0x2e, 0xa1, 0x6c, 0x1f, 0x36, 0x45, 0x18, 0xea, 0x59, 0x62, 0xb1, 0x2b, 0xfc,
	0x2d, 0x8a, 0x63, 0x15, 0x42, 0x86, 0x32, 0x1f, 0x74, 0x76, 0xab, 0xa2, 0x48, 0x26, 0xfe, 0x13,
	0x6a, 0x83, 0x2a, 0x84, 0x91, 0x55, 0xe6, 0x58, 0x5b, 0x7f, 0x9b, 0x74, 0x4e, 0xc0, 0x06, 0x8a,
	0x85, 0xb1, 0x03, 0x3d, 0x56, 0x09, 0xb9, 0xfa, 0x94, 0x1c, 0xa8, 0x83, 0x58, 0xb6, 0x08, 0x9c,
	0x89, 0xa9, 0x1b, 0x4d, 0x3b, 0x44, 0xaa, 0x61, 0xe8, 0x81, 0x1e, 0x8d, 0x62, 0x95, 0x38, 0xca,
	0x2e, 0x51, 0xaa, 0x10, 0xe6, 0x3c, 0x15, 0x99, 0x4c, 0xac, 0xcf, 0xe8, 0x01, 0xb9, 0xb4, 0x68,
	0xa4, 0xaf, 0x96, 0x1b, 0x09, 0x2b, 0xad, 0x6c, 0x24, 0xf6, 0x3d, 0x00, 0x36, 0xc2, 0xa9, 0xb4,
	0x42, 0xc5, 0xfe, 0x1e, 0xb1, 0xf7, 0xea, 0x6c, 0xa7, 0xe3, 0x15, 0x5e, 0x60, 0xa1, 0x5b, 0xd8,
	0xc1, 0xd7, 0x8e, 0x8a, 0x80, 0x54, 0x46, 0x74, 0x1d, 0xac, 0xb1, 0x4e, 0xa5, 0x09, 0xf3, 0xba,
	0xad, 0x83, 0x58, 0x33, 0xfd, 0xe9, 0x47, 0x29, 0xa2, 0x21, 0x1f, 0x50, 0x11, 0x7b, 0xbc, 0x04,
	0x82, 0xbf, 0x9a, 0x00, 0xa5, 0x43, 0xff, 0xb9, 0x4d, 0x7a, 0xd0, 0x4d, 0x54, 0x78, 0x97, 0x88,
	0x7c, 0x1f, 0x78, 0x7c, 0x21, 0x17, 0x73, 0x82, 0x74, 0x6e, 0x30, 0x2e, 0x64, 0x2c, 0x42, 0x65,
	0x4e, 0x26, 0x22, 0x19, 0xcb, 0x61, 0xc1, 0x71, 0xa3, 0x71, 0x05, 0x47, 0x3b, 0x99, 0x14, 0xf1,
	0x05, 0x72, 0xd6, 0x9d, 0x9d, 0x42, 0xc6, 0xa2, 0x49, 0x27, 0x3a, 0x91, 0xd4, 0x38, 0x1e, 0x77,
	0x02, 0x9e, 0x98, 0x48, 0x11, 0xf5, 0x43, 0x9d, 0x50, 0xb7, 0x78, 0x7c, 0x21, 0xe3, 0x09, 0x39,
	0xc5, 0xfc, 0x78, 0xee, 0x04, 0x09, 0x54, 0x66, 0x58, 0x4d, 0x97, 0xc2, 0x98, 0xb9, 0xce, 0x22,
	0xea, 0x08, 0x8f, 0xd7, 0x41, 0x2c, 0xa1, 0x54, 0xdc, 0x2f, 0x38, 0x9b, 0xae, 0xcc, 0x2b, 0x10,
	0xde, 0xac, 0xcc, 0x40, 0x8f, 0xf5, 0xcc, 0x52, 0x17, 0x74, 0xf9, 0x42, 0x0e, 0x7e, 0x6b, 0xc0,
	0xf6, 0x8d, 0x88, 0x63, 0x9c, 0x5f, 0xff, 0x73, 0x3a, 0xd1, 0x35, 0x1f, 0x32, 0x29, 0x7f, 0x75,
	0x61, 0xa7, 0x6b, 0x9c, 0x8c, 0xb3, 0xe8, 0x56, 0xc4, 0x22, 0x09, 0x5d, 0xd4, 0x9b, 0xbc, 0x10,
	0x71, 0xcd, 0xcc, 0xe9, 0x7e, 0x6a, 0xd2, 0x0e, 0x99, 0xab, 0x20, 0xc1, 0x31, 0x30, 0xe7, 0xdf,
	0x80, 0xa6, 0x77, 0xee, 0xe3, 0x5b, 0x68, 0xc7, 0x38, 0xea, 0x71, 0x15, 0x6c, 0x1e, 0xf9, 0xa5,
	0x8f, 0xf5, 0xb7, 0x70, 0x62, 0x05, 0xaf, 0xe1, 0x6b, 0x87, 0x9f, 0x49, 0x7b, 0x7c, 0x7f, 0xa3,
	0xaa, 0x2b, 0x7a, 0x5e, 0xce, 0xea, 0xb9, 0x8a, 0x96, 0xa8, 0xc3, 0xfe, 0xe9, 0xc3, 0x63, 0xfd,
	0x35, 0xec, 0x9e, 0x4c, 0x64, 0x78, 0x77, 0xad, 0xef, 0x64, 0x52, 0xd0, 0xf6, 0xa0, 0x63, 0x51,
	0xce, 0x89, 0x4e, 0x08, 0xde, 0x00, 0xab, 0x52, 0xf3, 0x47, 0x60, 0xd6, 0xb3, 0x4c, 0x67, 0x05,
	0x97, 0x84, 0xa3, 0x3f, 0xdb, 0xd0, 0xfe, 0x28, 0xe2, 0x98, 0xbd, 0x83, 0x8d, 0x0b, 0x39, 0xc7,
	0x0d, 0xc4, 0xfc, 0xfa, 0x9e, 0x2c, 0x7f, 0x32, 0x7a, 0xcf, 0xea, 0x9a, 0xc2, 0x76, 0xb0, 0xc6,
	0x4e, 0x00, 0xf2, 0x7f, 0x1e, 0xb4, 0xf0, 0x4d, 0x9d, 0x57, 0xfb, 0x1b, 0x7a, 0xc4, 0xc8, 0x8f,
	0xd0, 0x7d, 0xff, 0x59, 0x59, 0x32, 0xd1, 0xab, 0xb3, 0xaa, 0xeb, 0xf4, 0x11, 0x0b, 0xef, 0x60,
	0x03, 0x97, 0xe3, 0x17, 0x5e, 0x51, 0xee, 0xcc, 0x7f, 0x3c, 0x8e, 0x6d, 0x57, 0x3d, 0x5e, 0x5f,
	0xb9, 0xd5, 0xe3, 0xd5, 0x3d, 0x1b, 0xac, 0xb1, 0x73, 0xd8, 0x3e, 0x93, 0xd6, 0x65, 0x94, 0x32,
	0xcf, 0xbe, 0x5d, 0xae, 0x95, 0xa5, 0x9a, 0xe8, 0x3d, 0x58, 0x4c, 0xc1, 0x1a, 0xbb, 0x86, 0xdd,
	0x85, 0xb9, 0x2b, 0x19, 0x8f, 0xe8, 0xef, 0xf0, 0xcb, 0x16, 0xcb, 0xd2, 0xe9, 0x3d, 0x5f, 0x26,
	0x54, 0x4b, 0x39, 0x58, 0x63, 0x7d, 0x80, 0xb2, 0x3a, 0xaa, 0x99, 0x5a, 0x29, 0xaf, 0xaa, 0xa9,
	0xd5, 0x82, 0x0a, 0xd6, 0x6e, 0xd7, 0xe9, 0x2f, 0xfb, 0xbb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x70, 0x40, 0x70, 0xd0, 0x73, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HallClient is the client API for Hall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HallClient interface {
	// NewRoom 新建一个房间
	NewRoom(ctx context.Context, in *RoomAddRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	// UpdateRoom
	UpdateRoom(ctx context.Context, in *RoomUpdateRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	// ExitRoom
	ExitRoom(ctx context.Context, in *RoomExistRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	// GetRoom
	GetRoom(ctx context.Context, in *RoomGetRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	// GetUser
	GetUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// GetWalletByWid
	GetWalletByWid(ctx context.Context, in *WalletGetByWidRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	// GetWalletSelfList
	GetWalletSelfList(ctx context.Context, in *WalletGetByUIDRequest, opts ...grpc.CallOption) (*WalletListResponse, error)
	// CheckToken
	CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
}

type hallClient struct {
	cc *grpc.ClientConn
}

func NewHallClient(cc *grpc.ClientConn) HallClient {
	return &hallClient{cc}
}

func (c *hallClient) NewRoom(ctx context.Context, in *RoomAddRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/NewRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) UpdateRoom(ctx context.Context, in *RoomUpdateRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/UpdateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) ExitRoom(ctx context.Context, in *RoomExistRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/ExitRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) GetRoom(ctx context.Context, in *RoomGetRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) GetUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) GetWalletByWid(ctx context.Context, in *WalletGetByWidRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/GetWalletByWid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) GetWalletSelfList(ctx context.Context, in *WalletGetByUIDRequest, opts ...grpc.CallOption) (*WalletListResponse, error) {
	out := new(WalletListResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/GetWalletSelfList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hallClient) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := c.cc.Invoke(ctx, "/docsGrpc.Hall/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HallServer is the server API for Hall service.
type HallServer interface {
	// NewRoom 新建一个房间
	NewRoom(context.Context, *RoomAddRequest) (*RoomResponse, error)
	// UpdateRoom
	UpdateRoom(context.Context, *RoomUpdateRequest) (*RoomResponse, error)
	// ExitRoom
	ExitRoom(context.Context, *RoomExistRequest) (*RoomResponse, error)
	// GetRoom
	GetRoom(context.Context, *RoomGetRequest) (*RoomResponse, error)
	// GetUser
	GetUser(context.Context, *UserGetRequest) (*UserResponse, error)
	// GetWalletByWid
	GetWalletByWid(context.Context, *WalletGetByWidRequest) (*WalletResponse, error)
	// GetWalletSelfList
	GetWalletSelfList(context.Context, *WalletGetByUIDRequest) (*WalletListResponse, error)
	// CheckToken
	CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error)
}

// UnimplementedHallServer can be embedded to have forward compatible implementations.
type UnimplementedHallServer struct {
}

func (*UnimplementedHallServer) NewRoom(ctx context.Context, req *RoomAddRequest) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewRoom not implemented")
}
func (*UnimplementedHallServer) UpdateRoom(ctx context.Context, req *RoomUpdateRequest) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (*UnimplementedHallServer) ExitRoom(ctx context.Context, req *RoomExistRequest) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExitRoom not implemented")
}
func (*UnimplementedHallServer) GetRoom(ctx context.Context, req *RoomGetRequest) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (*UnimplementedHallServer) GetUser(ctx context.Context, req *UserGetRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedHallServer) GetWalletByWid(ctx context.Context, req *WalletGetByWidRequest) (*WalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletByWid not implemented")
}
func (*UnimplementedHallServer) GetWalletSelfList(ctx context.Context, req *WalletGetByUIDRequest) (*WalletListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletSelfList not implemented")
}
func (*UnimplementedHallServer) CheckToken(ctx context.Context, req *CheckTokenRequest) (*CheckTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}

func RegisterHallServer(s *grpc.Server, srv HallServer) {
	s.RegisterService(&_Hall_serviceDesc, srv)
}

func _Hall_NewRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).NewRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/NewRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).NewRoom(ctx, req.(*RoomAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).UpdateRoom(ctx, req.(*RoomUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_ExitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).ExitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/ExitRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).ExitRoom(ctx, req.(*RoomExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).GetRoom(ctx, req.(*RoomGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).GetUser(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_GetWalletByWid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletGetByWidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).GetWalletByWid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/GetWalletByWid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).GetWalletByWid(ctx, req.(*WalletGetByWidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_GetWalletSelfList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletGetByUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).GetWalletSelfList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/GetWalletSelfList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).GetWalletSelfList(ctx, req.(*WalletGetByUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hall_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HallServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docsGrpc.Hall/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HallServer).CheckToken(ctx, req.(*CheckTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docsGrpc.Hall",
	HandlerType: (*HallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewRoom",
			Handler:    _Hall_NewRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _Hall_UpdateRoom_Handler,
		},
		{
			MethodName: "ExitRoom",
			Handler:    _Hall_ExitRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _Hall_GetRoom_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Hall_GetUser_Handler,
		},
		{
			MethodName: "GetWalletByWid",
			Handler:    _Hall_GetWalletByWid_Handler,
		},
		{
			MethodName: "GetWalletSelfList",
			Handler:    _Hall_GetWalletSelfList_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _Hall_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hall.proto",
}
