package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
)

// Demo is the resolver for the demo field.
func (r *mutationResolver) Demo(ctx context.Context, hello string) (string, error) {
	panic(fmt.Errorf("not implemented: Demo - demo"))
}

// Demo is the resolver for the demo field.
func (r *queryResolver) Demo(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Demo - demo"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
